INSERT INTO registration_tokens (registration_token, user_role) VALUES('81b638ec-a6d0-4167-bb5e-409768492064', 'STUDENT');
INSERT INTO registration_tokens (registration_token, user_role) VALUES('4275fed8-c016-43fd-a216-331798d1d758', 'UNIVERSITY_EMPLOYEE');
INSERT INTO registration_tokens (registration_token, user_role) VALUES('62868339-1019-43d7-a7a9-df00c06022e3', 'ADMIN');

--insert into semesters (semester_number,year,id) values (?,?,?)
--insert into semesters (semester_number,year,id) values (?,?,?)
--insert into semesters (semester_number,year,id) values (?,?,?)
--insert into semesters (semester_number,year,id) values (?,?,?)
--insert into educational_modules (name,id) values (?,?)
--insert into educational_modules (name,id) values (?,?)
--insert into educational_modules (name,id) values (?,?)
--insert into educational_modules (name,id) values (?,?)
--insert into special_courses (control,credits_count,department,description,educational_module_id,name,teacher_name,id) values (?,?,?,?,?,?,?,?)
--insert into special_courses (control,credits_count,department,description,educational_module_id,name,teacher_name,id) values (?,?,?,?,?,?,?,?)
--insert into special_courses (control,credits_count,department,description,educational_module_id,name,teacher_name,id) values (?,?,?,?,?,?,?,?)
--insert into special_courses (control,credits_count,department,description,educational_module_id,name,teacher_name,id) values (?,?,?,?,?,?,?,?)
--insert into special_courses (control,credits_count,department,description,educational_module_id,name,teacher_name,id) values (?,?,?,?,?,?,?,?)
--insert into special_courses (control,credits_count,department,description,educational_module_id,name,teacher_name,id) values (?,?,?,?,?,?,?,?)
--insert into educational_programs (name,semester_id_to_required_credits_count,training_direction,id) values (?,?,?,?)
--insert into educational_programs (name,semester_id_to_required_credits_count,training_direction,id) values (?,?,?,?)
--insert into educational_program_to_courses_with_semesters (educational_program_id,is_required_course,semester_id,special_course_id,id) values (?,?,?,?,?)
--insert into educational_program_to_courses_with_semesters (educational_program_id,is_required_course,semester_id,special_course_id,id) values (?,?,?,?,?)
--insert into educational_program_to_courses_with_semesters (educational_program_id,is_required_course,semester_id,special_course_id,id) values (?,?,?,?,?)
--insert into educational_program_to_courses_with_semesters (educational_program_id,is_required_course,semester_id,special_course_id,id) values (?,?,?,?,?)
--insert into educational_program_to_courses_with_semesters (educational_program_id,is_required_course,semester_id,special_course_id,id) values (?,?,?,?,?)
--insert into educational_program_to_courses_with_semesters (educational_program_id,is_required_course,semester_id,special_course_id,id) values (?,?,?,?,?)
--insert into educational_program_to_courses_with_semesters (educational_program_id,is_required_course,semester_id,special_course_id,id) values (?,?,?,?,?)
--insert into educational_program_to_courses_with_semesters (educational_program_id,is_required_course,semester_id,special_course_id,id) values (?,?,?,?,?)
--insert into educational_program_to_courses_with_semesters (educational_program_id,is_required_course,semester_id,special_course_id,id) values (?,?,?,?,?)
--insert into educational_program_to_courses_with_semesters (educational_program_id,is_required_course,semester_id,special_course_id,id) values (?,?,?,?,?)
--select rt1_0.registration_token,rt1_0.user_role from registration_tokens rt1_0 where rt1_0.registration_token=?
--select rt1_0.registration_token,rt1_0.user_role from registration_tokens rt1_0 where rt1_0.registration_token=?
--select rt1_0.registration_token,rt1_0.user_role from registration_tokens rt1_0 where rt1_0.registration_token=?
--insert into registration_tokens (user_role,registration_token) values (?,?)
--insert into registration_tokens (user_role,registration_token) values (?,?)
--insert into registration_tokens (user_role,registration_token) values (?,?)
--select s1_0.id,s1_0.name from skills s1_0 where s1_0.id=?
--select s1_0.id,s1_0.name from skills s1_0 where s1_0.id=?
--select s1_0.id,s1_0.name from skills s1_0 where s1_0.id=?
--insert into skills (name,id) values (?,?)
--insert into skills (name,id) values (?,?)
--insert into skills (name,id) values (?,?)
--select null,s1_0.name from skills s1_0 where s1_0.id=?
--select null,s1_0.name from skills s1_0 where s1_0.id=?
--insert into courses_to_required_skills (required_skills_id,skill_level,special_course_id,id) values (?,?,?,?)
--insert into courses_to_required_skills (required_skills_id,skill_level,special_course_id,id) values (?,?,?,?)
--select null,s1_0.name from skills s1_0 where s1_0.id=?
--select null,s1_0.name from skills s1_0 where s1_0.id=?
--insert into courses_to_result_skills (skill_id,skill_level,special_course_id,id) values (?,?,?,?)
--insert into courses_to_result_skills (skill_id,skill_level,special_course_id,id) values (?,?,?,?)